[Xorg_xproto]
git-tree-sha1 = "cc77184c6d82cde3ed56f07bca571ebb8e6d1ec9"

    [[Xorg_xproto.download]]
    sha256 = "9b85f804b327057b069220a11386043e3443741a6153c4fdce55a6e264f62eb6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xproto_jll.jl/releases/download/Xorg_xproto-v7.0.31+2/Xorg_xproto.v7.0.31.any.tar.gz"
